#!/usr/bin/env bash
# Script that configures a new Ubuntu machine

# Update package repositories
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create the index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Define the redirection configuration
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"

# Replace the default configuration with the redirection configuration
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Define the 404 configuration
new_string="error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n}"

# Update Nginx configuration to use the custom 404 page
sudo sed -i "s@location \/ {[^}]*}@${new_string}@" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
