#!/usr/bin/env bash
# Script that configures a new Ubuntu machine

# Update package repositories
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create the index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Define the redirection configuration
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"

# Replace the default configuration with the redirection configuration
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default


# Add custom headers
sudo sed -i '/http {/a \ \ \ \ \ \ \ \ add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx restart
