#!/usr/bin/env bash
# This script that pings an IP address passed as an argument.

# Check if the correct number of arguments is provided
if [ "$#" -ne 1 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
else
	ping -c 5 "$1"
fi
