#!/usr/bin/env bash
# This script that uses ssh to connect to your server using the private
#+ key ~/.ssh/school with the user ubuntu.

# Define variables
server_address="100.25.197.208"
private_key="~/.ssh/school"

ssh -i "$private_key" ubuntu@"$server_address"
